# Generated by Django 5.2.8 on 2025-11-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('tenancy', '0002_remove_tenantdomain_tenant_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_key_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('RESELLER_ADMIN', 'Reseller Admin'), ('RESELLER_USER', 'Reseller User'), ('CLIENT_ADMIN', 'Client Admin'), ('CLIENT_USER', 'Client User')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenancy.tenant'),
        ),
    ]
