# Generated by Django 5.2.8 on 2025-11-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantdomain',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['tenant_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='wallet_enabled',
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#0057ff', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='#002266', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For a CLIENT, parent is Reseller or Platform. For RESELLER, parent is Platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tenancy.tenant'),
        ),
        migrations.DeleteModel(
            name='TenantBranding',
        ),
        migrations.DeleteModel(
            name='TenantDomain',
        ),
    ]
