# Generated by Django 5.2.8 on 2025-11-26 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tenant_type', models.CharField(choices=[('PLATFORM', 'Platform Owner'), ('RESELLER', 'Reseller'), ('CLIENT', 'Client')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('wallet_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='For CLIENT tenants under RESELLERS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True, null=True)),
                ('favicon', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#0057ff', max_length=20)),
                ('secondary_color', models.CharField(default='#002266', max_length=20)),
                ('dashboard_title', models.CharField(default='WeCallSMS Portal', max_length=200)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
    ]
